### ISSUE TITLE
mongodb-runner doesn't kill all instances

### ISSUE THREAD

**Issue by mtrezza** [mongodb-js/devtools-shared#483]
#### Current Behavior
When running `mongodb-runner stop --all`, the following error is thrown and the MongoDB instance is not stopped:

```
/node_modules/mongodb-runner/dist/cli.js:170
        throw err;
        ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:233:13)
    at MongoServer.close (/node_modules/mongodb-runner/dist/mongoserver.js:201:21)
    at /node_modules/mongodb-runner/dist/mongocluster.js:162:88
    at Array.map (<anonymous>)
    at MongoCluster.close (/node_modules/mongodb-runner/dist/mongocluster.js:162:61)
    at /node_modules/mongodb-runner/dist/runner-helpers.js:87:75
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async Object.stop (/node_modules/mongodb-runner/dist/runner-helpers.js:86:5)
    at async stop (/node_modules/mongodb-runner/dist/cli.js:121:9) {
  errno: -3,
  code: 'ESRCH',
  syscall: 'kill'
}

Node.js v18.18.2
```

#### Environment

- node.js / npm versions: 18.18.2
- OS: macos 14.5 (23F79)

**Comment by Moumouls** [comment]
It seems that there is an issue with mongo stop all

here a server created

```sh
> mongodb-runner start -t standalone

Server started and running at mongodb://127.0.0.1:54879/
Run the following command to stop the instance:
mongodb-runner stop --id=1ef1f912-597f-4e2e-9f2c-c63d4ed99801
```

Then an error on mongo stop all

```sh
> mongodb-runner stop --all

/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb-runner/dist/cli.js:170
        throw err;
        ^

MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Topology.selectServer (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/sdam/topology.js:303:38)
    at async Topology._connect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/sdam/topology.js:196:28)
    at async Topology.connect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/sdam/topology.js:158:13)
    at async topologyConnect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/mongo_client.js:223:17)
    at async MongoClient._connect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/mongo_client.js:236:13)
    at async MongoClient.connect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/mongo_client.js:161:13)
    at async MongoClient.connect (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb/lib/mongo_client.js:322:16)
    at async MongoServer.withClient (/Users/antoinecormouls/Desktop/Repos/parse/parse-server/node_modules/mongodb-runner/dist/mongoserver.js:221:24)
```

The stop system seems to try to connect to a 27017 port but there is no instances on this port

**Comment by addaleax** [comment]
@Moumouls I think a quick recommendation that we can give is that we've generally found it a bit nicer to use `mongodb-runner exec` instead of `mongodb-runner start` for automated usage, and leave the `start`/`stop` workflow mainly for human-facing usage.

`mongodb-runner exec` has two main advantages, namely, 1) automatically starting and stopping servers before/after a process runs, and 2) that it's an easy way to avoid port conflicts, because then `mongodb-runner` can just let the OS choose a free port for the new MongoDB process for you.

> Can the prune command also kill these dangling instances?

No, `prune` only checks which currently listed instances aren't running anymore. It's the opposite operation – it tries to find servers that aren't running anymore but which mongodb-runner still lists in its global server list.

> mongodb-runner has been used in the parse-server repo for a long time, but the issue started appearing in 2024. After the tests finish, we still see some running instances in the process tab, so restarting the server fails.

Interesting. Is running `npm test` on the parser-server repo enough to reproduce this?

**Comment by Moumouls** [comment]
Yes, @addaleax, if you want to try, you just need to:

* In one terminal, run `npm run watch` to build the server.
* In another terminal, run `npm run test spec/CloudCode.spec.js`, for example.

Launch it multiple times and you’ll see the error:
`Error: kill ESRCH`

P.S. I just checked, and the failure also occurs on the `parse-server` default branch (`alpha`), so you don’t waste time if you want to investigate.
